export default {
  labelSubtitle: "labelSubtitle",
  txtEmail: "txtEmail",
  txtPassword: "txtPassword",
  txtRepeatPassword: "txtRepeatPassword",
  txtName: "txtName",
  txtLastName: "txtLastName",
  txtPhone: "txtPhone",
  btnForgotPassword: "btnForgotPassword",
  btnLogin: "btnLogin",
  btnRegister: "btnRegister",
  btnContinue: "btnContinue",
  btnUpdate: "btnUpdate",
  btnBack: "btnBack",

  // Bottom Navigation:
  btnNavHome: "btnNavHome",
  btnNavCategories: "btnNavCategories",
  btnNavShoppingCart: "btnNavShoppingCart",
  btnNavProfile: "btnNavProfile",

  // Categories:
  txtSearch: "txtSearch",
  btnFilter: "btnFilter",
  btnApply: "btnApply",
  btnCancel: "btnCancel",
  switchAll: "switchAll",
  switchNew: "switchNew",
  switchPreOwned: "switchPreOwned",
  switchPrice: "switchPrice",
  switchRelevance: "switchRelevance",
  switchType: "switchType",
  radioGroup: "radioGroup",
  radioOption1: "radioOption1",
  radioOption2: "radioOption2",
  radioOption3: "radioOption3",
  radioOption4: "radioOption4",
  radioOption5: "radioOption5",
  radioOption6: "radioOption6",

  // Lists:
  item: "item",
  listProfile: "listProfile",
  listSettings: "listSettings",
};
