name: CI-CD
on:
  push:
    branches:
      - develop
      - qa
      - stage
      - main
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
jobs:
  ci:
    name: CI
    uses: DigitalFemsa-Genesys/module-pipelines/.github/workflows/react-native-pipeline.yml@main
    secrets: inherit
